### ___________________________________________________________________________________
@HOST=http://localhost:3001
### ___________________________________________________________________________________

GET {{HOST}}/ HTTP/1.1


### GET ALL EQUIPS
GET {{HOST}}/equips HTTP/1.1
Content-Type: application/json

### NEW EQUIP
POST {{HOST}}/new-equip HTTP/1.1
Content-Type: application/json

{
  "name": "Gabinete",
  "ambiente": "0"
}

### EQUIP 2 USER

POST {{HOST}}/equip2user HTTP/1.1
Content-Type: application/json

{
  "id":"01473b30-5ef4-11ed-bd54-d920d8ab1e5d",
  "user_id":"010ec610-5ef4-11ed-bd54-d920d8ab1e5d",
  "dt_saida": "2022-03-15", 
  "ambiente": "2"
}

