### ___________________________________________________________________________________
@HOST=http://localhost:3001
### ___________________________________________________________________________________

GET {{HOST}}/ HTTP/1.1

### SIGNUP
POST {{HOST}}/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "guilherme@teste",
  "password": "1234test",
  "admin": "1"
}

### LOGIN
POST {{HOST}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "joao@teste",
  "password": "1234test"
}

### GET ALL USERS
GET {{HOST}}/users HTTP/1.1
Content-Type: application/json

### DELETE A USER
DELETE  {{HOST}}/id/43084c00-5001-11ed-8456-11cc6393d037 HTTP/1.1
Content-Type: application/json

### LIST SINGLE USER
GET  {{HOST}}/user/957e7c30-5000-11ed-8456-11cc6393d037 HTTP/1.1
Content-Type: application/json

### UPDATE A USER
PUT {{HOST}}/id/957e7c30-5000-11ed-8456-11cc6393d037 HTTP/1.1
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "joao@teste",
  "password": "1234test",
  "admin": "1"
}