### ___________________________________________________________________________________
@HOST=http://localhost:3000
### ___________________________________________________________________________________

GET {{HOST}}/ HTTP/1.1

### SIGNUP
POST {{HOST}}/signup HTTP/1.1
Content-Type: application/json

{
  "name": "joao",
  "login": "jtmls",
  "password": "1234test",
  "equipment": ["BMW", "Ferrari"]
}

### LOGIN
POST {{HOST}}/login HTTP/1.1
Content-Type: application/json

{
  "login": "jtmls",
  "password": "1234test"
}

