### ___________________________________________________________________________________
@HOST=http://localhost:3001
### ___________________________________________________________________________________

GET {{HOST}}/ HTTP/1.1

### SIGNUP
POST {{HOST}}/signup HTTP/1.1
Content-Type: application/json

{
  "name": "Joao",
  "email": "joao@teste",
  "password": "1234test",
  "admin": "1"
}

### LOGIN
POST {{HOST}}/login HTTP/1.1
Content-Type: application/json

{
  "email": "joao@teste",
  "password": "1234test"
}

### GET ALL USERS
GET {{HOST}}/users HTTP/1.1
Content-Type: application/json

### DELETE A USER
DELETE  {{HOST}}/id/512abcc0-4d93-11ed-9342-1d5b10b95567 HTTP/1.1
Content-Type: application/json

### LIST SINGLE USER
GET  {{HOST}}/user/612312 HTTP/1.1
Content-Type: application/json

### UPDATE A USER
PUT {{HOST}}/id/b4120 HTTP/1.1
Content-Type: application/json

{
  "name": "Guilherme",
  "email": "joao@teste",
  "password": "1234test",
  "admin": "1"
}